# Generated by Django 5.2.8 on 2025-12-22 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streets', models.CharField(choices=[('', ''), ('SHKI', 'Шкільна'), ('GONT', 'Гонти'), ('LUKR', 'Лесі Українки'), ('MAZE', 'Мазепи'), ('BOGU', 'Богуна'), ('HMEL', 'Б. Хмельницького'), ('LISN', 'Лісна'), ('PIDL', 'Підлісна'), ('STUS', 'Стуса'), ('FRAN', 'І. Франка'), ('SAGA', 'Сагайдачного'), ('SHEV', 'Т. Шевченка'), ('BAND', 'С. Бандери')], default='', max_length=4, verbose_name='Вулиці')),
            ],
            options={
                'verbose_name': 'вулиця',
                'verbose_name_plural': 'Вулиці',
            },
        ),
        migrations.CreateModel(
            name='PostageItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=13, verbose_name='Track number')),
                ('delivered_date', models.DateTimeField()),
                ('recipient_street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flow_app_core.streetsmodel', verbose_name='Recipient street')),
            ],
            options={
                'verbose_name': 'postage item',
                'verbose_name_plural': 'Postage items',
                'ordering': ['delivered_date'],
            },
        ),
    ]
