# Generated by Django 5.2.8 on 2025-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postageItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=13, verbose_name='Track number')),
                ('recipient_street', models.CharField(max_length=20, verbose_name='Recipient street')),
                ('delivered_date', models.DateField()),
            ],
            options={
                'verbose_name': 'postage item',
                'verbose_name_plural': 'Postage items',
                'ordering': ['delivered_date'],
            },
        ),
    ]
