# Generated by Django 5.2.8 on 2025-12-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postageitemmodel',
            name='recipient_street',
            field=models.CharField(choices=[('', ''), ('SHKI', 'Шкільна'), ('GONT', 'Гонти'), ('LUKR', 'Лесі Українки'), ('MAZE', 'Мазепи'), ('BOGU', 'Богуна'), ('HMEL', 'Б. Хмельницького'), ('LISN', 'Лісна'), ('PIDL', 'Підлісна'), ('STUS', 'Стуса'), ('FRAN', 'І. Франка'), ('SAGA', 'Сагайдачного'), ('SHEV', 'Т. Шевченка'), ('BAND', 'С. Бандери')], max_length=4, verbose_name='Recipient street'),
        ),
    ]
