# Generated by Django 5.2.8 on 2025-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_app_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postageitemmodel',
            name='delivered_date',
            field=models.DateTimeField(),
        ),
    ]
