# Generated by Django 5.2.8 on 2025-12-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_app_core', '0002_alter_postageitemmodel_recipient_street'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreetsModel',
        ),
        migrations.AddField(
            model_name='postageitemmodel',
            name='small_package',
            field=models.BooleanField(default=False, verbose_name='Small package'),
        ),
    ]
