# Generated by Django 5.2.8 on 2025-12-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow_app_core', '0003_delete_streetsmodel_postageitemmodel_small_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='postageitemmodel',
            name='recipient_build',
            field=models.CharField(default=1, max_length=5, verbose_name='Recipient build'),
            preserve_default=False,
        ),
    ]
